apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resourses
  labels:
    app: online-inference
spec:
  containers:
    - image: skienbear/online-inference:v1
      name: online-inference
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "1Gi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "500m"